<?php
date_default_timezone_set('asia/bangkok');
session_start();
include "connectpcr.php";
		$sqllog = "INSERT INTO login_log (Emp_ID,ip) value ('".$_GET["emp"]."','".$_SERVER['REMOTE_ADDR']."')";
		$querylog = $conn->query($sqllog);
		$sql = "SELECT * FROM pcr_user WHERE usr_emp_code = '".$_GET["emp"]."'";
		$query = $conn->query($sql);
		$row = $query->fetch_assoc();
		$sqlemp = "SELECT * FROM employee WHERE Emp_ID = '".$_GET["emp"]."'";
		$queryemp = $condbmc->query($sqlemp);
		$rowemp = $queryemp->fetch_assoc();
		$sqlsec = "SELECT * FROM sectioncode WHERE Sectioncode = '".$rowemp["Sectioncode_ID"]."'";
		$querysec = $condbmc->query($sqlsec);
		$rowsec = $querysec->fetch_assoc();
		$sqlpos = "SELECT * FROM position WHERE Position_ID = '".$rowemp["Position_ID"]."'";
		$querypos = $condbmc->query($sqlpos);
		$rowpos = $querypos->fetch_assoc();
		$sqlcom = "SELECT * FROM company WHERE Company_ID = '".$rowemp["Company_ID"]."'";
		$querycom = $condbmc->query($sqlcom);
		$rowcom = $querycom->fetch_assoc();
		$_SESSION["empname_pcr"] = $rowemp["Empname_eng"];
		$_SESSION["emplast_pcr"] = $rowemp["Empsurname_eng"];
		$_SESSION["empid_pcr"] = $_GET["emp"];
		$_SESSION["sct_pcr"] = $rowsec["Sectioncode"];
		$_SESSION["dept_pcr"] = $rowsec["Department"];
		$_SESSION["postid_pcr"] = $rowpos["Position_ID"];
		$_SESSION["pos_pcr"] = $rowpos["Position_name"];
		$_SESSION["companyid_pcr"] = $rowcom["Company_ID"];
		$_SESSION["company_pcr"] = $rowcom["Company_shortname"];
		$_SESSION['role_pcr'] = $row["usr_rl_id"];	
		echo '<meta http-equiv=refresh content=0;URL=../INT/homepage.php>';
?>